---
# tasks file for swarmjoin
- name: "Print Hostvars"
  debug:
    var: hostvars['ansible']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] 

- name: "Add node to swarm"
  docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "{{ hostvars['ansible']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'ansible:2377' ]
