---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
    register: install_nginx_info
    failed_when: install_nginx_info.cache_update_time > 1

  - name: print install_nginx_info
    debug:
      msg: "{{ install_nginx_info }}"

  - name: Copy nginx file over
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    register: nginx_config

  - name: Print nginx copy file
    debug:
      msg: "{{ nginx_config }}"
    when: nginx_config.diff.after_path == nginx_config.diff.before.path

  - name: Restart nginx if needed
    service:
      name: nginx
      state: restarted
    when: nginx_config.changed == true