version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - "flask-app"
  flask-app:
    build: ./flask-app
    image: rwright1992/trio-app-jenkins
    depends_on:
    - "mysql"
  mysql:
    build: ./db
    image: rwright1992/trio-db-jenkins
    volumes:
    - type: volume
      source: triodb
      target: /var/lib/mysql

volumes:
  triodb:
