---
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: install python3 and pip
    apt:
      name:
        - python
        - python3-pip
        - python-pip
        - git
      state: true
      update_cache: true

  - name: install flask and pytest
    pip:
      name: 
        - flask
        - pytest